2023-05-23 23:14:01,523 INFO build_combined_normalized_csv(30) 199 sources selected to process
2023-05-23 23:14:05,756 INFO build_combined_normalized_csv(47) Source S-1 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:09,682 INFO build_combined_normalized_csv(47) Source S-2 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:09,924 INFO build_combined_normalized_csv(47) Source S-3 extract with 195 rows::: UnTreaties
2023-05-23 23:14:10,085 INFO build_combined_normalized_csv(47) Source S-4 extract with 195 rows::: UnTreaties
2023-05-23 23:14:14,051 INFO build_combined_normalized_csv(47) Source S-5 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:17,786 INFO build_combined_normalized_csv(47) Source S-6 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:20,407 INFO build_combined_normalized_csv(47) Source S-7 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:20,858 INFO build_combined_normalized_csv(47) Source S-15 extract with 954 rows::: DefaultJsonExtractor
2023-05-23 23:14:21,227 INFO build_combined_normalized_csv(47) Source S-16 extract with 954 rows::: DefaultJsonExtractor
2023-05-23 23:14:21,385 INFO build_combined_normalized_csv(47) Source S-17 extract with 381 rows::: DefaultJsonExtractor
2023-05-23 23:14:24,486 INFO build_combined_normalized_csv(47) Source S-18 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:26,885 INFO build_combined_normalized_csv(47) Source S-19 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:29,767 INFO build_combined_normalized_csv(47) Source S-20 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:32,959 INFO build_combined_normalized_csv(47) Source S-21 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:36,576 INFO build_combined_normalized_csv(47) Source S-22 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:40,142 INFO build_combined_normalized_csv(47) Source S-23 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:40,336 INFO build_combined_normalized_csv(47) Source S-24 extract with 195 rows::: UnTreaties
2023-05-23 23:14:44,152 INFO build_combined_normalized_csv(47) Source S-25 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:47,902 INFO build_combined_normalized_csv(47) Source S-26 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:51,788 INFO build_combined_normalized_csv(47) Source S-27 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:54,867 INFO build_combined_normalized_csv(47) Source S-28 extract with 195 rows::: ILO_Extractor
2023-05-23 23:14:55,114 INFO build_combined_normalized_csv(47) Source S-43 extract with 541 rows::: DefaultCSVExtractor
2023-05-23 23:14:55,321 INFO build_combined_normalized_csv(47) Source S-221 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:14:55,460 INFO build_combined_normalized_csv(47) Source S-46 extract with 379 rows::: DefaultCSVExtractor
2023-05-23 23:14:55,599 INFO build_combined_normalized_csv(47) Source S-47 extract with 409 rows::: DefaultCSVExtractor
2023-05-23 23:14:58,375 INFO build_combined_normalized_csv(47) Source S-48 extract with 195 rows::: ILO_Extractor
2023-05-23 23:15:01,131 INFO build_combined_normalized_csv(47) Source S-49 extract with 195 rows::: ILO_Extractor
2023-05-23 23:15:01,528 INFO build_combined_normalized_csv(47) Source S-50 extract with 195 rows::: UnTreaties
2023-05-23 23:15:01,710 INFO build_combined_normalized_csv(47) Source S-52 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:02,099 INFO build_combined_normalized_csv(47) Source S-53 extract with 970 rows::: DefaultJsonExtractor
2023-05-23 23:15:02,205 INFO build_combined_normalized_csv(47) Source S-62 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:02,360 INFO build_combined_normalized_csv(47) Source S-63 extract with 312 rows::: DefaultJsonExtractor
2023-05-23 23:15:02,486 INFO build_combined_normalized_csv(47) Source S-65 extract with 312 rows::: DefaultJsonExtractor
2023-05-23 23:15:02,684 INFO build_combined_normalized_csv(47) Source S-66 extract with 265 rows::: DefaultJsonExtractor
2023-05-23 23:15:02,822 INFO build_combined_normalized_csv(47) Source S-67 extract with 265 rows::: DefaultJsonExtractor
2023-05-23 23:15:02,867 INFO build_combined_normalized_csv(47) Source S-68 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:02,911 INFO build_combined_normalized_csv(47) Source S-69 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:02,956 INFO build_combined_normalized_csv(47) Source S-70 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:03,027 INFO build_combined_normalized_csv(47) Source S-71 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:03,187 INFO build_combined_normalized_csv(47) Source S-72 extract with 195 rows::: UnTreaties
2023-05-23 23:15:03,247 INFO build_combined_normalized_csv(47) Source S-74 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:03,324 INFO build_combined_normalized_csv(47) Source S-76 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:03,380 INFO build_combined_normalized_csv(47) Source S-77 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:03,441 INFO build_combined_normalized_csv(47) Source S-78 extract with 579 rows::: DefaultCSVExtractor
2023-05-23 23:15:03,503 INFO build_combined_normalized_csv(47) Source S-79 extract with 579 rows::: DefaultCSVExtractor
2023-05-23 23:15:03,549 INFO build_combined_normalized_csv(47) Source S-80 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:03,667 INFO build_combined_normalized_csv(47) Source S-81 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:03,750 INFO build_combined_normalized_csv(47) Source S-82 extract with 461 rows::: DefaultCSVExtractor
2023-05-23 23:15:03,824 INFO build_combined_normalized_csv(47) Source S-83 extract with 331 rows::: DefaultCSVExtractor
2023-05-23 23:15:03,998 INFO build_combined_normalized_csv(47) Source S-84 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:05,077 INFO build_combined_normalized_csv(47) Source S-85 extract with 1699 rows::: DefaultCSVExtractor
2023-05-23 23:15:05,177 INFO build_combined_normalized_csv(47) Source S-86 extract with 195 rows::: GlobalHealthObservatory
2023-05-23 23:15:05,277 INFO build_combined_normalized_csv(47) Source S-87 extract with 195 rows::: GlobalHealthObservatory
2023-05-23 23:15:05,435 INFO build_combined_normalized_csv(47) Source S-88 extract with 195 rows::: UnTreaties
2023-05-23 23:15:05,620 INFO build_combined_normalized_csv(47) Source S-89 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:05,790 INFO build_combined_normalized_csv(47) Source S-90 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:05,987 INFO build_combined_normalized_csv(47) Source S-91 extract with 561 rows::: DefaultCSVExtractor
2023-05-23 23:15:06,234 INFO build_combined_normalized_csv(47) Source S-92 extract with 195 rows::: UnTreaties
2023-05-23 23:15:06,352 INFO build_combined_normalized_csv(47) Source S-93 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:06,498 INFO build_combined_normalized_csv(47) Source S-98 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:06,664 INFO build_combined_normalized_csv(47) Source S-99 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:06,801 INFO build_combined_normalized_csv(47) Source S-102 extract with 207 rows::: DefaultJsonExtractor
2023-05-23 23:15:06,977 INFO build_combined_normalized_csv(47) Source S-103 extract with 444 rows::: DefaultCSVExtractor
2023-05-23 23:15:07,163 INFO build_combined_normalized_csv(47) Source S-108 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:07,349 INFO build_combined_normalized_csv(47) Source S-109 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:07,599 INFO build_combined_normalized_csv(47) Source S-110 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:07,770 INFO build_combined_normalized_csv(47) Source S-111 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:07,939 INFO build_combined_normalized_csv(47) Source S-112 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:08,107 INFO build_combined_normalized_csv(47) Source S-113 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:08,411 INFO build_combined_normalized_csv(47) Source S-114 extract with 195 rows::: CRIN_Treaties
2023-05-23 23:15:08,485 INFO build_combined_normalized_csv(47) Source S-119 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:08,533 INFO build_combined_normalized_csv(47) Source S-120 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:08,634 INFO build_combined_normalized_csv(47) Source S-121 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:08,740 INFO build_combined_normalized_csv(47) Source S-123 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:08,979 INFO build_combined_normalized_csv(47) Source S-124 extract with 195 rows::: UnTreaties
2023-05-23 23:15:09,152 INFO build_combined_normalized_csv(47) Source S-125 extract with 195 rows::: UnTreaties
2023-05-23 23:15:09,332 INFO build_combined_normalized_csv(47) Source S-126 extract with 195 rows::: UnTreaties
2023-05-23 23:15:09,539 INFO build_combined_normalized_csv(47) Source S-127 extract with 195 rows::: UnTreaties
2023-05-23 23:15:09,655 INFO build_combined_normalized_csv(47) Source S-128 extract with 195 rows::: UnTreaties
2023-05-23 23:15:09,705 INFO build_combined_normalized_csv(47) Source S-137 extract with 195 rows::: EITIIndicatorBuilder
2023-05-23 23:15:09,711 WARNING build_combined_normalized_csv(54) Source S-140 failed to extract cause of: 'Year'
Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 90, in build
    self.download().transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 109, in download
    self.dataframe = self._download()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/who.py", line 54, in _download
    s_157 = self.config.un_pop_tot.merge(
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/frame.py", line 10093, in merge
    return merge(
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 110, in merge
    op = _MergeOperation(
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 703, in __init__
    ) = self._get_merge_keys()
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1162, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'Year'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/run.py", line 44, in build_combined_normalized_csv
    extractor.build()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 100, in build
    raise ExtractionError(
etl.source_adapter.abstract.ExtractionError: Source S-140 failed to extract cause of: 'Year'
2023-05-23 23:15:09,929 INFO build_combined_normalized_csv(47) Source S-141 extract with 941 rows::: DefaultCSVExtractor
2023-05-23 23:15:10,019 INFO build_combined_normalized_csv(47) Source S-143 extract with 196 rows::: DefaultJsonExtractor
2023-05-23 23:15:10,117 INFO build_combined_normalized_csv(47) Source S-144 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:10,453 INFO build_combined_normalized_csv(47) Source S-145 extract with 195 rows::: UnTreaties
2023-05-23 23:15:10,547 INFO build_combined_normalized_csv(47) Source S-147 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:10,680 WARNING create_log_report_delete_duplicates(771) WARNING: There are 8 duplicate rows in the cleansed dataframe. Apart from soure S-166, this should not be the case. Check if you have mapped all columns (specifically the dimensions) and values. Now dropping duplicate rows and returning dataframe without duplicates.
2023-05-23 23:15:10,700 INFO build_combined_normalized_csv(47) Source S-149 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:11,339 INFO build_combined_normalized_csv(47) Source S-151 extract with 195 rows::: ICRC_Treaties
2023-05-23 23:15:11,925 INFO build_combined_normalized_csv(47) Source S-152 extract with 195 rows::: ICRC_Treaties
2023-05-23 23:15:12,528 INFO build_combined_normalized_csv(47) Source S-153 extract with 195 rows::: ICRC_Treaties
2023-05-23 23:15:12,635 INFO build_combined_normalized_csv(47) Source S-154 extract with 195 rows::: UnTreaties
2023-05-23 23:15:12,737 INFO build_combined_normalized_csv(47) Source S-155 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:13,061 INFO build_combined_normalized_csv(47) Source S-156 extract with 195 rows::: UnTreaties
2023-05-23 23:15:16,852 INFO build_combined_normalized_csv(47) Source S-157 extract with 195 rows::: ILO_Extractor
2023-05-23 23:15:16,945 INFO build_combined_normalized_csv(47) Source S-160 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:17,044 INFO build_combined_normalized_csv(47) Source S-220 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:18,229 INFO build_combined_normalized_csv(47) Source S-163 extract with 195 rows::: IDMC_Extractor
2023-05-23 23:15:18,467 INFO build_combined_normalized_csv(47) Source S-164 extract with 195 rows::: UnTreaties
2023-05-23 23:15:18,653 INFO build_combined_normalized_csv(47) Source S-165 extract with 417 rows::: DefaultJsonExtractor
2023-05-23 23:15:18,997 INFO build_combined_normalized_csv(47) Source S-166 extract with 509 rows::: DefaultJsonExtractor
2023-05-23 23:15:19,223 INFO build_combined_normalized_csv(47) Source S-167 extract with 399 rows::: UN_SDG_UN_POP
2023-05-23 23:15:19,352 INFO build_combined_normalized_csv(47) Source S-168 extract with 195 rows::: UN_SDG_UN_POP
2023-05-23 23:15:19,481 INFO build_combined_normalized_csv(47) Source S-169 extract with 195 rows::: UN_SDG_UN_POP
2023-05-23 23:15:19,764 INFO build_combined_normalized_csv(47) Source S-170 extract with 195 rows::: UN_SDG_UN_POP
2023-05-23 23:15:20,929 INFO build_combined_normalized_csv(47) Source S-171 extract with 195 rows::: IDMC_Extractor
2023-05-23 23:15:23,216 INFO build_combined_normalized_csv(47) Source S-172 extract with 195 rows::: Inform_Risk_Index_Data
2023-05-23 23:15:23,539 INFO build_combined_normalized_csv(47) Source S-173 extract with 195 rows::: UnTreaties
2023-05-23 23:15:23,642 INFO build_combined_normalized_csv(47) Source S-174 extract with 195 rows::: UnTreaties
2023-05-23 23:15:23,941 INFO build_combined_normalized_csv(47) Source S-175 extract with 195 rows::: CRIN_Treaties
2023-05-23 23:15:24,114 INFO build_combined_normalized_csv(47) Source S-180 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:24,232 INFO build_combined_normalized_csv(47) Source S-181 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:26,386 INFO build_combined_normalized_csv(47) Source S-184 extract with 1259 rows::: DefaultJsonExtractor
2023-05-23 23:15:26,455 INFO build_combined_normalized_csv(47) Source S-186 extract with 579 rows::: DefaultCSVExtractor
2023-05-23 23:15:26,609 INFO build_combined_normalized_csv(47) Source S-187 extract with 363 rows::: DefaultCSVExtractor
2023-05-23 23:15:26,683 INFO build_combined_normalized_csv(47) Source S-188 extract with 579 rows::: DefaultCSVExtractor
2023-05-23 23:15:26,765 INFO build_combined_normalized_csv(47) Source S-189 extract with 579 rows::: DefaultCSVExtractor
2023-05-23 23:15:26,949 INFO build_combined_normalized_csv(47) Source S-193 extract with 715 rows::: DefaultJsonExtractor
2023-05-23 23:15:28,139 INFO build_combined_normalized_csv(47) Source S-194 extract with 4945 rows::: DefaultCSVExtractor
2023-05-23 23:15:28,246 INFO build_combined_normalized_csv(47) Source S-196 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:28,331 INFO build_combined_normalized_csv(47) Source S-197 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:28,512 INFO build_combined_normalized_csv(47) Source S-198 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:28,710 INFO build_combined_normalized_csv(47) Source S-199 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:29,934 INFO build_combined_normalized_csv(47) Source S-200 extract with 3187 rows::: DefaultCSVExtractor
2023-05-23 23:15:30,329 INFO build_combined_normalized_csv(47) Source S-201 extract with 445 rows::: DefaultJsonExtractor
2023-05-23 23:15:30,501 INFO build_combined_normalized_csv(47) Source S-202 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:30,604 INFO build_combined_normalized_csv(47) Source S-203 extract with 196 rows::: DefaultJsonExtractor
2023-05-23 23:15:30,704 INFO build_combined_normalized_csv(47) Source S-204 extract with 196 rows::: DefaultJsonExtractor
2023-05-23 23:15:30,954 INFO build_combined_normalized_csv(47) Source S-205 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:31,122 INFO build_combined_normalized_csv(47) Source S-206 extract with 453 rows::: DefaultJsonExtractor
2023-05-23 23:15:31,222 INFO build_combined_normalized_csv(47) Source S-207 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:32,516 INFO build_combined_normalized_csv(47) Source S-209 extract with 195 rows::: IDMC_Extractor
2023-05-23 23:15:32,643 INFO build_combined_normalized_csv(47) Source S-213 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:32,768 INFO build_combined_normalized_csv(47) Source S-215 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:32,877 INFO build_combined_normalized_csv(47) Source S-216 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:32,982 INFO build_combined_normalized_csv(47) Source S-217 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:33,341 INFO build_combined_normalized_csv(47) Source S-218 extract with 195 rows::: DefaultJsonExtractor
2023-05-23 23:15:33,415 INFO build_combined_normalized_csv(47) Source S-8 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:33,467 INFO build_combined_normalized_csv(47) Source S-9 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:33,850 INFO build_combined_normalized_csv(47) Source S-10 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:34,236 WARNING build_combined_normalized_csv(54) Source S-11 failed to extract cause of: '[None] not in index'
Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 90, in build
    self.download().transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 109, in download
    self.dataframe = self._download()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/manual.py", line 131, in _download
    self.dataframe = self.dataframe.loc[
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1256, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 924, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1301, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1239, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: '[None] not in index'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/run.py", line 44, in build_combined_normalized_csv
    extractor.build()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 100, in build
    raise ExtractionError(
etl.source_adapter.abstract.ExtractionError: Source S-11 failed to extract cause of: '[None] not in index'
2023-05-23 23:15:34,712 INFO build_combined_normalized_csv(47) Source S-13 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:35,125 INFO build_combined_normalized_csv(47) Source S-29 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:35,213 INFO build_combined_normalized_csv(47) Source S-33 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:35,278 INFO build_combined_normalized_csv(47) Source S-34 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:35,395 WARNING build_combined_normalized_csv(54) Source S-35 failed to extract cause of: 'RAW_OBS_VALUE'
Traceback (most recent call last):
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'RAW_OBS_VALUE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 90, in build
    self.download().transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 127, in transform
    self.dataframe = self._transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/wpa.py", line 121, in _transform
    self.dataframe_cleansed = cleanse.encode_categorical_variables(
  File "/home/lasse/Development/crba-allinone/etl/transformation/cleanse.py", line 702, in encode_categorical_variables
    dataframe[obs_raw_value_source].astype(
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'RAW_OBS_VALUE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/run.py", line 44, in build_combined_normalized_csv
    extractor.build()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 100, in build
    raise ExtractionError(
etl.source_adapter.abstract.ExtractionError: Source S-35 failed to extract cause of: 'RAW_OBS_VALUE'
2023-05-23 23:15:35,512 WARNING build_combined_normalized_csv(54) Source S-36 failed to extract cause of: 'RAW_OBS_VALUE'
Traceback (most recent call last):
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'RAW_OBS_VALUE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 90, in build
    self.download().transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 127, in transform
    self.dataframe = self._transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/wpa.py", line 121, in _transform
    self.dataframe_cleansed = cleanse.encode_categorical_variables(
  File "/home/lasse/Development/crba-allinone/etl/transformation/cleanse.py", line 702, in encode_categorical_variables
    dataframe[obs_raw_value_source].astype(
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'RAW_OBS_VALUE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/run.py", line 44, in build_combined_normalized_csv
    extractor.build()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 100, in build
    raise ExtractionError(
etl.source_adapter.abstract.ExtractionError: Source S-36 failed to extract cause of: 'RAW_OBS_VALUE'
2023-05-23 23:15:35,632 WARNING create_log_report_delete_duplicates(771) WARNING: There are 1 duplicate rows in the cleansed dataframe. Apart from soure S-166, this should not be the case. Check if you have mapped all columns (specifically the dimensions) and values. Now dropping duplicate rows and returning dataframe without duplicates.
2023-05-23 23:15:35,637 WARNING build_combined_normalized_csv(54) Source S-37 failed to extract cause of: Unable to parse string "VALUE WITHOUT MAPPING - PLEASE MAP" at position 65
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 2369, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "VALUE WITHOUT MAPPING - PLEASE MAP"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 90, in build
    self.download().transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 127, in transform
    self.dataframe = self._transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/wpa.py", line 142, in _transform
    self.dataframe_normalized = scaler.normalizer(
  File "/home/lasse/Development/crba-allinone/etl/transformation/scaler.py", line 63, in normalizer
    cleansed_data[raw_data_col] = pd.to_numeric(raw_obs_value)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/tools/numeric.py", line 185, in to_numeric
    values, _ = lib.maybe_convert_numeric(
  File "pandas/_libs/lib.pyx", line 2411, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "VALUE WITHOUT MAPPING - PLEASE MAP" at position 65

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/run.py", line 44, in build_combined_normalized_csv
    extractor.build()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 100, in build
    raise ExtractionError(
etl.source_adapter.abstract.ExtractionError: Source S-37 failed to extract cause of: Unable to parse string "VALUE WITHOUT MAPPING - PLEASE MAP" at position 65
2023-05-23 23:15:36,089 INFO build_combined_normalized_csv(47) Source S-38 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:36,495 INFO build_combined_normalized_csv(47) Source S-40 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:36,716 INFO build_combined_normalized_csv(47) Source S-51 extract with 195 rows::: Global_Slavery_Index
2023-05-23 23:15:36,782 INFO build_combined_normalized_csv(47) Source S-54 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:36,849 INFO build_combined_normalized_csv(47) Source S-55 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:36,915 INFO build_combined_normalized_csv(47) Source S-56 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:36,980 INFO build_combined_normalized_csv(47) Source S-57 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:37,045 INFO build_combined_normalized_csv(47) Source S-58 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:37,112 INFO build_combined_normalized_csv(47) Source S-59 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:37,283 INFO build_combined_normalized_csv(47) Source S-73 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:37,372 INFO build_combined_normalized_csv(47) Source S-75 extract with 195 rows::: FCTC_Data
2023-05-23 23:15:37,493 INFO build_combined_normalized_csv(47) Source S-94 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:37,624 INFO build_combined_normalized_csv(47) Source S-95 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:37,736 INFO build_combined_normalized_csv(47) Source S-96 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:38,135 WARNING build_combined_normalized_csv(54) Source S-97 failed to extract cause of: '[None] not in index'
Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 90, in build
    self.download().transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 109, in download
    self.dataframe = self._download()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/manual.py", line 131, in _download
    self.dataframe = self.dataframe.loc[
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1256, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 924, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1301, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1239, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: '[None] not in index'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/run.py", line 44, in build_combined_normalized_csv
    extractor.build()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 100, in build
    raise ExtractionError(
etl.source_adapter.abstract.ExtractionError: Source S-97 failed to extract cause of: '[None] not in index'
2023-05-23 23:15:38,596 WARNING build_combined_normalized_csv(54) Source S-101 failed to extract cause of: '[None] not in index'
Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 90, in build
    self.download().transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 109, in download
    self.dataframe = self._download()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/manual.py", line 131, in _download
    self.dataframe = self.dataframe.loc[
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1256, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 924, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1301, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1239, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: '[None] not in index'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/run.py", line 44, in build_combined_normalized_csv
    extractor.build()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 100, in build
    raise ExtractionError(
etl.source_adapter.abstract.ExtractionError: Source S-101 failed to extract cause of: '[None] not in index'
2023-05-23 23:15:38,711 INFO build_combined_normalized_csv(47) Source S-105 extract with 195 rows::: KidsRightsIndex
2023-05-23 23:15:38,816 INFO build_combined_normalized_csv(47) Source S-106 extract with 195 rows::: KidsRightsIndex
2023-05-23 23:15:38,919 INFO build_combined_normalized_csv(47) Source S-107 extract with 195 rows::: KidsRightsIndex
2023-05-23 23:15:39,323 WARNING build_combined_normalized_csv(54) Source S-117 failed to extract cause of: '[None] not in index'
Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 90, in build
    self.download().transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 109, in download
    self.dataframe = self._download()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/manual.py", line 131, in _download
    self.dataframe = self.dataframe.loc[
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1256, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 924, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1301, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1239, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: '[None] not in index'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/run.py", line 44, in build_combined_normalized_csv
    extractor.build()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 100, in build
    raise ExtractionError(
etl.source_adapter.abstract.ExtractionError: Source S-117 failed to extract cause of: '[None] not in index'
2023-05-23 23:15:39,383 INFO build_combined_normalized_csv(47) Source S-118 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:39,529 INFO build_combined_normalized_csv(47) Source S-129 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:39,631 INFO build_combined_normalized_csv(47) Source S-131 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:39,746 INFO build_combined_normalized_csv(47) Source S-132 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:39,853 INFO build_combined_normalized_csv(47) Source S-133 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:39,966 INFO build_combined_normalized_csv(47) Source S-134 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:40,076 INFO build_combined_normalized_csv(47) Source S-135 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:40,168 INFO build_combined_normalized_csv(47) Source S-136 extract with 195 rows::: Climate_Watch_Data_Paris_Contributions
2023-05-23 23:15:40,254 INFO build_combined_normalized_csv(47) Source S-142 extract with 195 rows::: Climate_Watch_Data_S_159
2023-05-23 23:15:40,362 INFO build_combined_normalized_csv(47) Source S-148 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:40,429 INFO build_combined_normalized_csv(47) Source S-150 extract with 195 rows::: Landmark_Data
2023-05-23 23:15:40,633 INFO build_combined_normalized_csv(47) Source S-176 extract with 195 rows::: KidsRightsIndex
2023-05-23 23:15:40,734 INFO build_combined_normalized_csv(47) Source S-177 extract with 195 rows::: KidsRightsIndex
2023-05-23 23:15:40,839 INFO build_combined_normalized_csv(47) Source S-178 extract with 195 rows::: KidsRightsIndex
2023-05-23 23:15:40,942 INFO build_combined_normalized_csv(47) Source S-179 extract with 195 rows::: KidsRightsIndex
2023-05-23 23:15:41,347 WARNING build_combined_normalized_csv(54) Source S-208 failed to extract cause of: '[None] not in index'
Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 90, in build
    self.download().transform()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 109, in download
    self.dataframe = self._download()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/manual.py", line 131, in _download
    self.dataframe = self.dataframe.loc[
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1256, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 924, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1301, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1239, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/lasse/.cache/pypoetry/virtualenvs/crba-project-5qZtH06h-py3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: '[None] not in index'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lasse/Development/crba-allinone/etl/run.py", line 44, in build_combined_normalized_csv
    extractor.build()
  File "/home/lasse/Development/crba-allinone/etl/source_adapter/abstract.py", line 100, in build
    raise ExtractionError(
etl.source_adapter.abstract.ExtractionError: Source S-208 failed to extract cause of: '[None] not in index'
2023-05-23 23:15:41,436 INFO build_combined_normalized_csv(47) Source S-210 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:41,518 INFO build_combined_normalized_csv(47) Source S-211 extract with 195 rows::: WPA_Extractor
2023-05-23 23:15:41,646 INFO build_combined_normalized_csv(47) Source S-212 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:41,796 INFO build_combined_normalized_csv(47) Source S-214 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:41,918 INFO build_combined_normalized_csv(47) Source S-12 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:42,044 INFO build_combined_normalized_csv(47) Source S-41 extract with 739 rows::: DefaultCSVExtractor
2023-05-23 23:15:42,122 INFO build_combined_normalized_csv(47) Source S-42 extract with 310 rows::: DefaultCSVExtractor
2023-05-23 23:15:42,207 INFO build_combined_normalized_csv(47) Source S-44 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:42,253 INFO build_combined_normalized_csv(47) Source S-185 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:42,303 INFO build_combined_normalized_csv(47) Source S-190 extract with 195 rows::: DefaultCSVExtractor
2023-05-23 23:15:42,418 INFO build_combined_normalized_csv(47) Source S-100 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:42,560 INFO build_combined_normalized_csv(47) Source S-122 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:43,383 INFO build_combined_normalized_csv(47) Source S-138 extract with 195 rows::: NRGI
2023-05-23 23:15:44,125 INFO build_combined_normalized_csv(47) Source S-139 extract with 195 rows::: NRGI
2023-05-23 23:15:44,223 INFO build_combined_normalized_csv(47) Source S-219 extract with 195 rows::: HumanEnteredBlueprintIndicatorBuilder
2023-05-23 23:15:45,478 INFO build_combined_normalized_csv(47) Source S-162 extract with 195 rows::: IDMC_Extractor
